/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vetclinic;

import javax.swing.JOptionPane;

/**
 *
 * @author coco
 */
public class client_log extends javax.swing.JFrame {

    /**
     * Creates new form client_log
     */
    public client_log() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("CLIENT LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("CLIENT NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("CLIENT ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 120, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 93, -1));

        jButton3.setBackground(new java.awt.Color(0, 255, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 85, -1));

        jButton4.setBackground(new java.awt.Color(255, 51, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 285, 73, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\coco\\Downloads\\catclient.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 500, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         home info = new home();
            info.setVisible(true);
             dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField1.setText(null);
        jTextField2.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
              String username = jTextField1.getText();
        String password = jTextField2.getText();
if (    username.equals("CHINMAY")&&password.equals("01"))
{
    jTextField1.setText(null);
     jTextField2.setText(null);
    display_c info = new display_c();
    info.setVisible(true);
    dispose();
}
else if (    username.equals("SRUJANA")&&password.equals("02"))
{
    jTextField1.setText(null);
     jTextField2.setText(null);
    display_c info = new display_c();
    info.setVisible(true);
    dispose();
}
else if (    username.equals("PRADHUYTH")&&password.equals("03"))
{
    jTextField1.setText(null);
     jTextField2.setText(null);
    display_c info = new display_c();
    info.setVisible(true);
    dispose();
}
else if (    username.equals("RACHANA")&&password.equals("04"))
{
    jTextField1.setText(null);
     jTextField2.setText(null);
    display_c info = new display_c();
    info.setVisible(true);
    dispose();
}
else if (    username.equals("SAKSHI")&&password.equals("05"))
{
    jTextField1.setText(null);
     jTextField2.setText(null);
   display_c info = new display_c();
    info.setVisible(true);
    dispose();
}
else if (    username.equals("ANKITH")&&password.equals("06"))
{
    jTextField1.setText(null);
     jTextField2.setText(null);
    display_c info = new display_c();
    info.setVisible(true);
    dispose();
}
else if (    username.equals("THAVESH")&&password.equals("07"))
{
    jTextField1.setText(null);
     jTextField2.setText(null);
    display_c info = new display_c();
    info.setVisible(true);
    dispose();
}
else if (    username.equals("NISHA")&&password.equals("08"))
{
    jTextField1.setText(null);
     jTextField2.setText(null);
    display_c info = new display_c();
    info.setVisible(true);
    dispose();
}
else if (    username.equals("MEDHA")&&password.equals("09"))
{
    jTextField1.setText(null);
     jTextField2.setText(null);
    display_c info = new display_c();
    info.setVisible(true);
    dispose();
}
else if (    username.equals("SHALINI")&&password.equals("10"))
{
    jTextField1.setText(null);
     jTextField2.setText(null);
    display_c info = new display_c();
    info.setVisible(true);
    dispose();
}
else if (    username.equals("PRATHANA")&&password.equals("11"))
{
    jTextField1.setText(null);
     jTextField2.setText(null);
    display_c info = new display_c();
    info.setVisible(true);
    dispose();
}
else if (    username.equals("SUNETHRA")&&password.equals("12"))
{
    jTextField1.setText(null);
     jTextField2.setText(null);
    display_c info = new display_c();
    info.setVisible(true);
    dispose();
}
else if (    username.equals("MANASA")&&password.equals("13"))
{
    jTextField1.setText(null);
     jTextField2.setText(null);
     display_c info = new display_c();
    info.setVisible(true);
    dispose();
}
else
{
    JOptionPane.showMessageDialog(null, "invalid","error",JOptionPane.ERROR_MESSAGE);
    jTextField1.setText(null);
     jTextField2.setText(null);
}            



    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(client_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(client_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(client_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(client_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new client_log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
